[package]
name = "xbrl-rs"
version = "0.2.0"
edition = "2024"
authors = ["quambene <contact.quambene@gmail.com>"]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/quambene/xbrl-rs"
repository = "https://github.com/quambene/xbrl-rs"
documentation = "https://docs.rs/xbrl-rs"
description = "XBRL parser and validation"
keywords = ["xbrl", "parser",  "taxes", "accounting", "finance"]
categories = ["finance"]
include = [
  "src/**",
  "!src/bin/**",
  "README.md",
  "LICENSE",
  "CHANGELOG.md",
  "Cargo.toml"
]

[features]
default = []
download = ["dep:reqwest"]
logger = ["dep:env_logger"]
# Feature flag to run the taxonomy test suite.
taxonomy-test = []
# Feature flag to run the conformance test suite.
conformance-test = []

[dependencies]
thiserror = "2"
log = "0.4"
indexmap = "2"
rust_decimal = "1"
chrono = "0.4"
quick-xml = "0.39"
env_logger = { version = "0.11", optional = true }
reqwest = { version = "0.12", optional = true, default-features = false, features = ["blocking", "rustls-tls"] }

[dev-dependencies]
assert_matches = "1.5"
criterion = { version = "0.5", features = ["html_reports"] }
roxmltree = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bench]]
name = "bench_xbrl"
harness = false

[[bin]]
name = "download_taxonomies"
path = "src/bin/download_taxonomies.rs"
required-features = ["download", "logger"]
