[package]
name = "xbrl-rs"
version = "0.1.1"
edition = "2024"
authors = ["quambene <contact.quambene@gmail.com>"]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/quambene/xbrl-rs"
repository = "https://github.com/quambene/xbrl-rs"
documentation = "https://docs.rs/xbrl-rs"
description = "XBRL parser and validation"
keywords = ["xbrl", "parser",  "taxes", "accounting", "finance"]
categories = ["finance"]
include = [
  "src/**",
  "!src/bin/**",
  "tests/**",
  "README.md",
  "LICENSE",
  "CHANGELOG.md",
  "Cargo.toml"
]

[dependencies]
thiserror = "2.0"
env_logger = "0.11.8"
log = "0.4.29"
quick-xml = "0.39.0"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }

[dev-dependencies]
roxmltree = "0.21.1"
